/* maintenance/music-links.mjs — generates the soundtrack download list.
 *
 * Reads the track table from src/ui/music.js (menu track + run pool: title, file, tier) and the
 * actual files in media/music/, then writes docs/soundtrack-downloads.md with one download URL
 * per track. Files present on disk but not referenced by music.js are listed separately, so a
 * track that was dropped from the pool but kept in the repo still shows up.
 *
 * Usage:
 *   node maintenance/music-links.mjs
 *   npm run music:links
 */
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const MUSIC_JS = join(ROOT, "src/ui/music.js");
const ASSET_DIR = join(ROOT, "media/music");
const OUT = join(ROOT, "docs/soundtrack-downloads.md");

// Download base. The media files live in the repository and are additionally published to
// gh-pages by .github/workflows/deploy-media.yml. raw.githubusercontent serves the repository
// copy and is pinned to a branch, which is what a download list wants.
const REF = process.env.MUSIC_LINKS_REF || "main";
const RAW_BASE = `https://raw.githubusercontent.com/GitGudMonkeh/autostich/${REF}/media/music`;
const PAGES_BASE = "https://gitgudmonkeh.github.io/autostich/media/music";

const src = readFileSync(MUSIC_JS, "utf8");

// Track constants: variable name -> file name. music.js builds URLs via `const x = track("x")`.
const files = new Map();
for (const m of src.matchAll(/const\s+(\w+)\s*=\s*track\("([^"]+)"\)/g)) {
  files.set(m[1], `${m[2]}.m4a`);
}

const orderMatch = src.match(/const\s+TIER_ORDER\s*=\s*\[([^\]]*)\]/);
const TIER_ORDER = orderMatch
  ? [...orderMatch[1].matchAll(/"([^"]+)"/g)].map((x) => x[1])
  : ["calm", "mid", "hot", "overdrive", "overdrive_plus"];

const entries = [];
const menuMatch = src.match(/const\s+MENU_TRACK\s*=\s*\{\s*title:\s*"([^"]+)"\s*,\s*url:\s*(\w+)/);
if (menuMatch) entries.push({ title: menuMatch[1], file: files.get(menuMatch[2]), tier: "menu" });
for (const m of src.matchAll(/\{\s*title:\s*"([^"]+)"\s*,\s*url:\s*(\w+)\s*,\s*tier:\s*"([^"]+)"\s*\}/g)) {
  entries.push({ title: m[1], file: files.get(m[2]), tier: m[3] });
}

const onDisk = new Set(readdirSync(ASSET_DIR).filter((f) => f.endsWith(".m4a")));
const referenced = new Set(entries.map((e) => e.file).filter(Boolean));
const orphans = [...onDisk].filter((f) => !referenced.has(f)).sort();

const mb = (file) => {
  try { return `${(statSync(join(ASSET_DIR, file)).size / 1048576).toFixed(1)} MB`; } catch { return "—"; }
};
const row = (e) => {
  const missing = !e.file || !onDisk.has(e.file);
  const link = missing ? "**file missing**" : `[${e.file}](${RAW_BASE}/${e.file})`;
  return `| ${e.title} | ${link} | ${missing ? "—" : mb(e.file)} |`;
};

const TIER_LABEL = {
  menu: "Menu / Victory",
  calm: "calm",
  mid: "mid",
  hot: "hot",
  overdrive: "overdrive",
  overdrive_plus: "overdrive+",
};

const out = [];
out.push("# Soundtrack — download links");
out.push("");
out.push("Generated by `npm run music:links` from `src/ui/music.js` and `media/music/`.");
out.push("Re-run it after adding, renaming or re-tiering a track; the list is not updated automatically.");
out.push("");
out.push(`Links point at the repository copy on \`${REF}\`. The same files are published to GitHub Pages`);
out.push(`under \`${PAGES_BASE}/\` by \`.github/workflows/deploy-media.yml\`.`);
out.push("");
out.push("Run durations per track and per tier: `npm run music:overview`.");
out.push("");
out.push("## Download all at once");
out.push("");
out.push("```bash");
out.push("# sparse clone — music only, no app sources");
out.push("git clone --depth 1 --filter=blob:none --sparse https://github.com/GitGudMonkeh/autostich.git");
out.push("cd autostich && git sparse-checkout set media/music");
out.push("```");
out.push("");
out.push("```bash");
out.push("# or pull the files straight out of this list");
out.push("grep -o 'https://raw\\.githubusercontent\\.com/[^)]*\\.m4a' docs/soundtrack-downloads.md \\");
out.push("  | sort -u | xargs -n1 -P4 curl -fLO --output-dir ./soundtrack");
out.push("```");
out.push("");

for (const tier of ["menu", ...TIER_ORDER]) {
  const rows = entries.filter((e) => e.tier === tier);
  if (!rows.length) continue;
  out.push(`## ${TIER_LABEL[tier] || tier}`);
  out.push("");
  out.push("| Title | File | Size |");
  out.push("| --- | --- | --- |");
  for (const e of rows) out.push(row(e));
  out.push("");
}

if (orphans.length) {
  out.push("## Not referenced by `music.js`");
  out.push("");
  out.push("Present in `media/music/`, currently not played by the game.");
  out.push("");
  out.push("| File | Size |");
  out.push("| --- | --- |");
  for (const f of orphans) out.push(`| [${f}](${RAW_BASE}/${f}) | ${mb(f)} |`);
  out.push("");
}

writeFileSync(OUT, out.join("\n"), "utf8");
console.log(`docs/soundtrack-downloads.md written — ${entries.length} referenced, ${orphans.length} unreferenced.`);
