#!/usr/bin/env node
/* #menu-rework MH2 — the page-side scripts the survey installs before the module graph runs.
   ============================================================================

   PROMOTED FROM `docs/workstreams/desktop-menus/evidence/M8/seed.mjs`, NOT REWRITTEN. M8 built and
   proved these two sources; they sat task-local, so only M8's own harness ever installed them, and
   every other run of `viewport-survey.mjs` went without. That is what this file ends. `seed.mjs`
   now re-exports from here, so there is exactly one copy and it cannot drift into two.

   THE ONE THING THIS FILE CHANGES ABOUT A SURVEY RUN, stated plainly: nothing the application can
   see. `leaderboardConfigured` stays true, `PREVIEW` stays false, every code path is the one that
   ships. What moves is where the answer to an `autostich_scores` request comes from, and what
   `Date.now()` returns.

   WHY IT IS THE SURVEY'S BUSINESS AND NOT THE APPLICATION'S. `publishRun` (leaderboard.js:106) is
   gated by `VITE_PREVIEW` alone, and the survey measures the PRODUCTION build on purpose — a
   baseline taken through a preview build is a baseline of something nobody plays. So the write is
   real, the gate is real, and the only place left to stop it is the browser the survey drives.
   MH2 item 1: the check asked "is this a preview build?" where it should have asked "is this a real
   player?".

   THREE THINGS IT SETTLES AT ONCE, and none of them is a side effect:

     1. THE LIVE WRITE. The survey seeds `as_username = "SURVEY"` and its `victory` cell ends a run,
        so a full matrix posts up to ten real rows into `autostich_scores`. Invisible in every gate,
        because the score never reaches the top twenty. `fetchStubSource()` answers every URL
        containing `autostich_scores` locally — the POST included — so the insert never leaves the
        browser.

     2. THE WALL CLOCK (MENU-30). The hub reads the ISO week behind every overlay and the ranked tab
        renders a countdown that ticks every second. One `<span>` crossing midnight cost this
        workstream 72 box deltas across 37 cells and 10 surfaces. `freezeClockSource()` pins it.

     3. THE ROW COUNT (TYPO-08). The leaderboard's row count followed whatever the live table held at
        the moment of the run, so two halves of a comparison were two different screens. Against a
        fixed table it is the same number by construction — M8 measured 20 and 20 in all 60 of its
        cells.

   NOTHING HERE READS THE CLOCK OR THE RANDOM SOURCE. Re-running produces the same bytes, which is
   the only property that makes a before/after pair a comparison. */

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));

/* THE FROZEN INSTANT. Monday, 2026-08-24, 12:00 UTC — the middle of a week, so no rounding sits near
   a boundary. Both halves of any comparison get the same week label, the same week seed and the same
   countdown string, whatever day they are actually taken on. */
export const FROZEN_MS = Date.UTC(2026, 7, 24, 12, 0, 0);

/* ------------------------------------------------------------------ the board

   Twenty rows, generated by arithmetic rather than typed, so the table cannot drift while someone
   edits it. What varies row to row is what the LIST shows: rank tone (the first three), name length
   (the truncation case), archetype icon count (0 to 3), tree progress (including the missing value
   that renders the dashed pill), and cycle count.

   Row 4 carries the empty `tree_nodes` on purpose: `TreePill` renders a DASHED "-/27" for it, which
   is a second visual state that no capture would otherwise contain.
   Row 8 carries the long name — past the point where `truncate` bites in the narrow cockpit column. */
const ARCH = ["", "fire", "lightning,fire", "fire,ice", "lightning,fire,ice", "plant", "ice,plant"];
const NAMES = ["Vexil", "Nomad", "Kestrel", "Bo", "Sable", "Quill", "Wren",
  "Ferrothorn-Ueberbau", "Ash", "Mirek", "Tuli", "Odessa", "Prow", "Kite", "Halcyon",
  "Bram", "Sooth", "Ivor", "Lace", "Wend"];

export function boardRows(limit = 20, board = null, seed = null) {
  const n = Math.max(0, Math.min(NAMES.length, Number(limit) || 0));
  const rows = [];
  for (let i = 0; i < n; i++) {
    rows.push({
      id: 9000 + i,
      name: NAMES[i],
      score: 1284000 - i * 41137,
      level: 6 - (i % 3),
      tricks: 88 - i,
      cycles: 9 - (i % 5),
      archetypes: ARCH[i % ARCH.length],
      best_streak: 7 - (i % 4),
      perks: "",
      skills: "",
      max_formations: 3 + (i % 3),
      formation_score: 12000 - i * 311,
      crits: 14 - (i % 6),
      wins: 40 - i,
      crit_bonus_score: 9400 - i * 173,
      best_trick_score: 31000 - i * 517,
      /* Row 4 has no tree value: the dashed pill is a state of its own and belongs in the capture. */
      tree_nodes: i === 3 ? null : 27 - ((i * 3) % 27),
      seed: seed != null ? Number(seed) : 4000000 + i * 7,
      board: board || null,
      created_at: "2026-08-" + String(10 + (i % 14)).padStart(2, "0") + "T09:00:00Z",
    });
  }
  return rows;
}

/* THE STUB, as source text. It is installed as an init script so it is in place before the module
   graph runs — `leaderboard.js` reads `import.meta.env` at module scope, and a stub installed after
   that has already missed the first fetch. Only `autostich_scores` is intercepted; every other
   request (the bundle, the fonts, the media) goes to the real network untouched.

   THE MATCH IS ON THE TABLE NAME AND NOT ON THE METHOD, and that is what makes this a write barrier
   rather than a read fixture: `publishRun` POSTs to the same REST path the board GETs, so the table
   name catches the insert on the same line that catches the read. There is no `if (method === "GET")`
   to fall through here, and there must never be one.

   The champion archive asks for `limit = 1` per expired week, ten times. Giving every week the same
   winner would hide the row's own variance, so the name rotates with the week seed — deterministic,
   because the seed is a function of the week and the week is frozen. */
export function fetchStubSource({ champions = true } = {}) {
  const rows = JSON.stringify(boardRows(NAMES.length));
  const names = JSON.stringify(NAMES);
  return "(() => {\n"
    + "  const ALL = " + rows + ";\n"
    + "  const NAMES = " + names + ";\n"
    + "  const json = (v) => new Response(JSON.stringify(v), { status: 200, headers: { \"content-type\": \"application/json\" } });\n"
    + "  const real = window.fetch.bind(window);\n"
    + "  window.fetch = function (input, init) {\n"
    + "    const url = typeof input === \"string\" ? input : (input && input.url) || \"\";\n"
    + "    if (url.indexOf(\"autostich_scores\") < 0) return real(input, init);\n"
    + "    const limit = Math.max(0, Math.min(ALL.length, Number((/[?&]limit=(\\d+)/.exec(url) || [])[1] || 20)));\n"
    + "    const seedM = /[?&]seed=eq\\.(\\d+)/.exec(url);\n"
    + "    const boardM = /[?&]board=eq\\.([^&]+)/.exec(url);\n"
    + "    if (seedM && limit === 1) {\n"
    + (champions
      ? "      const i = Math.abs(Number(seedM[1])) % NAMES.length;\n"
        + "      return Promise.resolve(json([Object.assign({}, ALL[i], { seed: Number(seedM[1]), board: \"meister\" })]));\n"
      /* `champions: false` is what re-measures the design's open question 1: the EMPTY challenger tab
         and the card height it produces. An empty archive is a real state — a fresh table, or ten
         weeks nobody played — and it is the state the design took its 347 px from. */
      : "      return Promise.resolve(json([]));\n")
    + "    }\n"
    + "    const out = ALL.slice(0, limit).map((r) => Object.assign({}, r, {\n"
    + "      board: boardM ? decodeURIComponent(boardM[1]) : null,\n"
    + "      seed: seedM ? Number(seedM[1]) : r.seed,\n"
    + "    }));\n"
    + "    return Promise.resolve(json(out));\n"
    + "  };\n"
    + "  return true;\n"
    + "})()";
}

/* Pin the clock. `Date.now()` and `new Date()` both, because `currentWeek(new Date(now))` uses the
   constructor and `msUntilWeekEnd` uses it again — freezing only one of the two leaves the countdown
   live. `performance.now()` is deliberately left alone: React's scheduler reads it, and a frozen
   monotonic clock is a hung scheduler, not a still screen. */
export function freezeClockSource(ms = FROZEN_MS) {
  return "(() => {\n"
    + "  const FIXED = " + ms + ";\n"
    + "  const Real = Date;\n"
    + "  function Frozen(...a) {\n"
    + "    if (!(this instanceof Frozen)) return new Real(FIXED).toString();\n"
    + "    return a.length ? new Real(...a) : new Real(FIXED);\n"
    + "  }\n"
    + "  Frozen.prototype = Real.prototype;\n"
    + "  Frozen.now = () => FIXED;\n"
    + "  Frozen.parse = Real.parse;\n"
    + "  Frozen.UTC = Real.UTC;\n"
    + "  window.Date = Frozen;\n"
    + "  return FIXED;\n"
    + "})()";
}

/* ------------------------------------------------------------------ the run count

   MH2 item 3, §8.12. The survey's cells are NOT independent: every `victory` cell ends a run, and
   `recordRun` (storage.js:410) prepends it to `as_runhistory`, which nothing clears between cells.
   So the first cell of a browser session sees 0 completed runs and the tenth sees 9, and four
   surfaces read that number.

   It is deterministic and it cancels between two halves of a comparison — but a reader looking at ONE
   matrix cannot tell a known accumulation from a regression, and that is what this exports. The count
   is not derived and not assumed: it is READ from the same key the application reads, at the moment
   the probe runs, and written into the cell.

   `-1` is the "could not read" answer, and it is deliberately not `0`: a storage exception recorded
   as an empty history would be a wrong number rather than a missing one. */
export function runCountSource() {
  return "(() => { try {\n"
    + "  const raw = localStorage.getItem(\"as_runhistory\");\n"
    + "  const a = raw ? JSON.parse(raw) : [];\n"
    + "  return Array.isArray(a) ? a.length : -1;\n"
    + "} catch (e) { return -1; } })()";
}

if (process.argv[1] && process.argv[1].endsWith("survey-stub.mjs")) {
  if (process.argv.includes("--write")) {
    writeFileSync(join(HERE, "survey-stub.json"), JSON.stringify({ rows: boardRows() }, null, 1));
    console.log("survey-stub.json written — " + boardRows().length + " board rows");
  } else {
    console.log("board rows " + boardRows().length
      + " · frozen " + new Date(FROZEN_MS).toISOString()
      + " · fetch stub " + fetchStubSource().length + " chars"
      + " · clock stub " + freezeClockSource().length + " chars"
      + " · run count " + runCountSource().length + " chars");
  }
}
